server:
  port: 4000

spring:
  application:
    name: registration-service
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: registration-service 