server:
  port: 4000

spring:
  application:
    name: registration-service
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: registration-service