version: '3.8'

networks:
  microservices-network:
    driver: bridge

services:
  eureka-server:
    build: ./services/eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  registration-service-database:
    image: postgres:latest
    container_name: registration-service-database
    networks:
      - microservices-network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  registration-service:
    build: ./services/service-registration
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
      registration-service-database:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://registration-service-database:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
      SPRING_KAFKA_PRODUCER_KEY-SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE-SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
    ports:
      - "4000:4000"

  student-service-database:
    image: postgres:latest
    container_name: student-service-database
    networks:
      - microservices-network
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U student_user -d student_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  course-service-database:
    image: postgres:latest
    container_name: course-service-database
    networks:
      - microservices-network
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U course_user -d course_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  student-service:
    build: ./services/student-service
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
      student-service-database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://student-service-database:5432/student_db
      SPRING_DATASOURCE_USERNAME: student_user
      SPRING_DATASOURCE_PASSWORD: student_password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4001:4001"

  course-service:
    build: ./services/course-service
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
      course-service-database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-service-database:5432/course_db
      SPRING_DATASOURCE_USERNAME: course_user
      SPRING_DATASOURCE_PASSWORD: course_password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4002:4002"

  api-gateway:
    build: ./gateway
    networks:
      - microservices-network
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      registration-service:
        condition: service_started
      student-service:
        condition: service_started
      course-service:
        condition: service_started

  auth-service:
    build: ./services/auth-service
    environment:
      - NODE_ENV=production
      - JWT_SECRET=nhom17
      - JWT_EXPIRES_IN=1h
      - PORT=4004
    ports:
      - "4004:4004"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  notification-service:
    build: ./services/notification-service
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
      SPRING_KAFKA_CONSUMER_GROUP-ID: notification-group
      SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET: earliest
      SPRING_KAFKA_CONSUMER_KEY-DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "*"
    ports:
      - "4005:4005"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - microservices-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "echo srvr | nc localhost 2181 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - microservices-network
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
