server:
  port: 4002

spring:
  application:
    name: course-service
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 24 hours in milliseconds
      cache-null-values: false

logging:
  level:
    root: INFO
    com.example.courseservice: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: course-service
