server:
  port: 4002

spring:
  application:
    name: course-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://course-service-database:5432/course_db
    username: ${SPRING_DATASOURCE_USERNAME:course_user}
    password: ${SPRING_DATASOURCE_PASSWORD:course_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: course-service 