server:
  port: 4002

spring:
  application:
    name: course-service
  cloud:
    compatibility-verifier:
      enabled: false



eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: course-service
