server:
  port: 4001

spring:
  application:
    name: student-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://student-service-database:5432/student_db
    username: ${SPRING_DATASOURCE_USERNAME:student_user}
    password: ${SPRING_DATASOURCE_PASSWORD:student_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: student-service 