### Create a new student
POST http://localhost:4000/students
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "dateOfBirth": "2003-03-19",
  "address": "Ha Noi",
  "phone": "0123456788"

}
