server:
  port: 4005

spring:
  application:
    name: notification-service
  cloud:
    compatibility-verifier:
      enabled: false
  
  kafka:
    bootstrap-servers: kafka:29092
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuhoan159357@gmail.com
    password: lnvd voun vzlh vurb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: notification-service
    instance-id: ${spring.application.name}:4004
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health 